version: '3'
services:
  postgres:
    image: postgres:16.1
    ports:
      - "5432:5432"
    environment:
      POSTGRESS_USERNAME: postgres
      POSTGRES_PASSWORD: admin
      POSTGRESS_DB: event-service
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 8000
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    restart: always

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  broker:
    image: confluentinc/cp-kafka:latest
    container_name: broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1


  naming-server:
    image: nipun2123/naming-service:1.0.0
    container_name: naming-service
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - zipkin

  api-gateway-server:
    image: nipun2123/api-gateway:1.0.0
    container_name: api-gateway-server
    ports:
      - "8765:8765"
    expose:
      - "8765"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY= TRACE'
    networks:
      - vibzvenue-network
    depends_on:
      - zipkin
      - naming-server

  event-server:
    image: nipun2123/event-service:1.0.0
    container_name: event-server
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - postgres
      - zipkin
      - naming-server
      - api-gateway-server

  user-server:
    image: nipun2123/user-service:1.0.0
    container_name: user-server
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - event-server
      - broker
      - zipkin
      - naming-server
      - api-gateway-server


  notification-server:
    image: nipun2123/notification-server:1.0.0
    container_name: notification-server
    ports:
      - "8787:8787"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - broker
      - zipkin
      - naming-server
      - api-gateway-server

networks:
  vibzvenue-network:

volumes:
  postgres-data:



