services:
  postgres:
    image: postgres:16.1
    ports:
      - "5432:5432"
    environment:
      POSTGRESS_USERNAME: postgres
      POSTGRES_PASSWORD: admin
      POSTGRESS_DB: event-service
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 8000
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"

volumes:
  postgres-data:



